version: "3.7"

services:
 app:
  image: node:20-alpine
  networks:
   - todo-app
  command: sh -c "yarn install && yarn run start:prod"
  ports:
   - 3000:3000
  working_dir: /app
  volumes:
   - ./:/app
  environment:
   MYSQL_HOST: mysql
   MYSQL_USER: root
   MYSQL_PASSWORD: Akhil123#
   MYSQL_DB: todos
 mysql:
  image: mysql:8.3
  networks:
   - todo-app
  volumes:
   - todo-mysql-data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: Akhil123#
   MYSQL_DATABASE: todos
   MYSQL_ALLOW_EMPTY_PASSWORD: true
  ports:
   - 3308:3308
volumes:
 todo-mysql-data:

networks:
 todo-app:
  external: true
